
theme = "dark_plus"

[editor]
line-number = "relative"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[keys.normal]
"space" = { o = "file_picker_in_current_buffer_directory" }
