
theme = "dark_plus"

[editor]
line-number = "relative"
mouse = false

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[keys.normal]
"space" = { o = "file_picker_in_current_buffer_directory" }

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
