[[language]]
name = "cpp"
scope = "source.cpp"
injection-regex = "cpp"
file-types = ["cc", "hh", "c++", "cpp", "hpp", "h", "ipp", "tpp", "cxx", "hxx", "ixx", "txx", "ino", "C", "H", "cu", "cuh", "cppm", "h++", "ii", "inl", { glob = ".hpp.in" }, { glob = ".h.in" }]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = [ "clangd" ]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"

[[language]]
name = "lua"
language-servers = ["lua-language-server"]
# Optional: auto format, settings, etc.
auto-format = true

[languages.shell]
tab_size = 4
expand_tabs = true  # Enable converting tabs to spaces
